title: '@octylFractal'
email: octavia.togami@gmail.com
baseurl: "/"
url: "https://octyl.net"

# Special variables:
github_username: octylFractal

permalink: /:categories/:year/:month/:day/:title/

sass:
  style: compressed

exclude:
  - .idea
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
